name: CI Release

on:
  push:
    branches:
      - 'rel_*'
      - 'main'
      - 'master'

jobs:
  package-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # min
          - php-version: "7.3"

          # 8.x
          - php-version: "8.0"

          # max
          - php-version: "8.2"

    name: PHP ${{ matrix.php-version }} tests

    steps:
      - uses: actions/checkout@v4

      - name: Run package tests
        uses: d3datadevelopment/ci-actions/composer-package-test@v1
        with:
          php_version: ${{ matrix.php-version }}
          syntax_check_paths: "src,Tests"
          test_suites: "linkmobility"

  report-status:
    runs-on: ubuntu-latest
    needs: package-tests
    if: always()
    steps:
      - name: Report CI status
        uses: d3datadevelopment/ci-actions/status-reporter@v1
        with:
          api_status_endpoint: "${{ vars.GITEA_API }}${{ github.sha }}"
          auth_token: ${{ secrets.GITEA_TOKEN }}
          state: ${{ needs.package-tests.result }}
          description: "CI result: ${{ needs.package-tests.result }}"
          target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
